USE worldnews;

-- INSERTS--------------------------------------

--
-- insert into 'users'
--

INSERT INTO `users` VALUES(NULL, 'Juan', 'Rivas', 'juanjo207', 'journalist', 'activo', 'juan@juan.com', '+34 675938528', '$2y$12$/KpQiMmVlvKXFTCZOQxtX.rilC7/bAONlGKtJ7vZJWv/KrM9EwSbu', curtime(), curtime(), NULL),
                          (NULL, 'Luis', 'Sandoval', 'administrador 1', 'admin', 'activo', 'admin@admin.com', '+34 634078326', '$2y$12$/KpQiMmVlvKXFTCZOQxtX.rilC7/bAONlGKtJ7vZJWv/KrM9EwSbu', curtime(), curtime(), NULL),
                          (NULL, 'Jaime', 'Roca', 'editor 1', 'editor', 'activo', 'editor@editor.com', '+34 634078326', '$2y$12$/KpQiMmVlvKXFTCZOQxtX.rilC7/bAONlGKtJ7vZJWv/KrM9EwSbu', curtime(), curtime(), NULL),
                          (NULL, 'nombre1', 'apellido1', 'username1', 'journalist', 'activo', 'user1@user1.com', '+34 634078326', '$2y$12$/KpQiMmVlvKXFTCZOQxtX.rilC7/bAONlGKtJ7vZJWv/KrM9EwSbu', curtime(), curtime(), NULL);

--
-- insert into 'sections'
--

INSERT INTO `sections` VALUES(NULL, 2, 'Política Nacional', 'activo', curtime(), curtime()),
                             (NULL, 2, 'Política Internacional', 'activo', curtime(), curtime()),
                             (NULL, 2, 'Economía', 'activo', curtime(), curtime()),
                             (NULL, 2, 'Deportes', 'activo', curtime(), curtime());


--
-- insert into 'articles'
--

INSERT INTO `articles` VALUES(NULL, 1, NULL, 4, 'Final de la Copa del Rey', 'sub título del artículo', 'copadelrey.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pretium sapien id sem scelerisque, in fermentum nibh tempor. In auctor ligula in nunc malesuada convallis. Nulla venenatis iaculis elit et venenatis. Nulla ac velit egestas, sagittis sem vestibulum, auctor justo. Suspendisse sit amet posuere felis. In tempus odio ut quam vehicula, non dictum sem hendrerit. Cras non vulputate magna, vitae facilisis nibh. Etiam aliquet, turpis at porta mattis, nisl leo pellentesque libero, nec convallis purus felis in eros. Maecenas vel nisi ipsum. Sed porttitor est sit amet placerat congue. ', 'kw1;wk2;kw3', 'final-de-la-copa-del-rey', 'publicado', null, curtime(), curtime(), curtime());
INSERT INTO `articles` VALUES(NULL, 1, NULL, 1, 'El PP apuesta por nuevas elecciones y activa la maquinaria del partido', 'Insiste en una alianza electoral con Cs ante la previsión de otros comicios', 'politica-01.jpg', 'El PP entra en modo campaña. Y ha dado ya los primeros pasos para activar la maquinaria electoral: la dirección del partido contempla, en previsión de una repetición electoral el 10-N, reforzar su estructura en las 28 circunscripciones que reparten cinco diputados o menos, donde la competencia de Vox hizo mella en abril. La insistencia en aliarse con Ciudadanos demuestra que en Génova piensan que la probabilidad de nuevas elecciones es muy elevada. Tras firmar el peor resultado del PP, y con Ciudadanos a la baja en las encuestas, Pablo Casado pretende consolidarse en el bloque de la derecha si el PSOE no desencalla la investidura.', 'pp;elecciones', 'El-PP-apuesta-por-nuevas-elecciones', 'publicado', null, curtime(), curtime(), curtime());
INSERT INTO `articles` VALUES(NULL, 1, NULL, 1, 'Torra insiste en su desafío y dice que trabajará “sin tregua” por la independencia', 'El president reclama a Pedro Sánchez "un diálogo de tú a tú, hablando de todo"', 'politica-02.jpg', 'La víspera de acudir al juicio que se celebrará este lunes en el Tribunal Superior de Justicia de Cataluña para ser juzgado por un delito de desobediencia, el presidente de la Generalitat, Quim Torra, ha insistido este domingo en su desafío al Estado. En un mensaje en Twitter con motivo de cumplir año y medio en el cargo, Torra ha declarado su "compromiso para trabajar, sin tregua, para culminar el proceso de independencia". El mandatario catalán recuerda que cuando prometió el cargo lo hizo "con fidelidad a la voluntad del pueblo de Cataluña representada en el Parlament".', 'torra;catalunya;independencia', 'Torra-insiste-en-su-desafío-independentista', 'publicado', null, curtime(), curtime(), curtime());
INSERT INTO `articles` VALUES(NULL, 1, NULL, 1, 'Zapatero, sobre el acuerdo entre PSOE y Unidas Podemos: “Deseaba que se produjera”', 'El expresidente del Gobierno apuesta por un diálogo en Cataluña donde se puedan plantear todas las alternativas', 'politica-03.jpg', 'El expresidente del Gobierno José Luis Rodríguez Zapatero ha asegurado que “deseaba” que se produjera el preacuerdo de Gobierno con el que PSOE y Unidas Podemos. “El acuerdo con el que nos han sorprendido esta semana me ha parecido muy bien. Yo deseaba que se produjera”, ha asegurado este domingo el expresidente del Ejecutivo en una entrevista en el programa de la cadena SER A vivir que son dos días.', 'psoe;zapatero;podemos', 'Zapatero-sobre-el-acuerdo-entre-PSOE-y-Unidas-Podemos', 'publicado', null, curtime(), curtime(), curtime());
INSERT INTO `articles` VALUES(NULL, 1, NULL, 3, 'Gxchain realiza la primera donación importante al Blockchain Lab de la Universidad Stony Brook', 'Blockchain Business Lab está ayudando a los estudiantes a avanzar en el aprendizaje sobre esta tecnología', 'economia-01.png', 'El propio laboratorio de negocios Blockchain de la Universidad de Stony Brook en el College of Business recibió la donación de 2 años de la compañía de tecnología de datos GXChain.

GXChain es el primer donante corporativo del laboratorio blockchain, una compañía que lidera la economía de datos global al ayudar a los desarrolladores a crear aplicaciones blockchain que son parte de la creciente industria de blockchain y criptomonedas.

Blockchain Business Lab se creó en 2018 para la investigación de aplicaciones comerciales de blockchain en medio de la creciente industria de blockchain y criptografía, y recluta estudiantes voluntarios para ayudar en la realización de proyectos académicos y de investigación de la industria. El profesor Danling Jiang, decano asociado de investigación y desarrollo de la facultad en el College of Business, es codirector del laboratorio con el profesor Stoyan Stoyanov y trabaja con los estudiantes voluntarios para ayudarlos a desarrollar mentalidades de investigación con respecto a esta tecnología emergente.

“Queremos que estos estudiantes tengan exposición a esta tecnología e industria”, dijo, “a través de la creación de networking con personas de este espacio, ya sea haciendo investigaciones relevantes para las empresas en este espacio, y alentar a nuestros estudiantes a crear productos o aplicaciones o un negocio de su propio.

Blockchain es una tecnología emergente que se prevé que revolucionará la forma en que se hacen los negocios en la economía moderna y podría aplicarse mucho más allá de los usos de la criptomoneda.

Blockchain Business Lab está ayudando a los estudiantes a avanzar en el aprendizaje sobre esta tecnología, aplicándola a otros aspectos de los negocios, como el financiamiento y el comercio a través de proyectos de investigación que colaboran con profesores y socios de la industria como BitMart Lab.

Los estudiantes se ofrecen como voluntarios en estos proyectos para ayudar con la investigación, como recopilar datos, evaluar el riesgo y el retorno de invertir en el espacio, y comprender las regulaciones financieras relevantes, para estudiar el aspecto comercial de esta industria en crecimiento y cómo podría afectar la economía moderna en el futuro cercano.

Gran parte de esta donación otorgada por GXChain financiará premios de excelencia en investigación para que los estudiantes reconozcan adecuadamente su arduo trabajo y resultados exitosos en el laboratorio como voluntarios no remunerados. Varios estudiantes han comenzado a crear sus propias empresas utilizando las herramientas que aprendieron, e incluso han regresado al laboratorio como “mentores de la industria” para dirigir proyectos de investigación para otros estudiantes. Se alienta a los estudiantes a aprender y crear y comenzar sus negocios o ideas que puedan llevar con ellos.

“A través de esta exposición y trabajo en equipo, pueden construir una red con profesionales de la industria, investigadores y entre ellos, y potencialmente perseguir futuras carreras en este espacio emergente”, agregó el profesor Jiang. “Nuestra misión es alentar a los estudiantes a aprender, crear y comenzar sus negocios o ideas que puedan llevar con ellos

”.', 'bitcoin;criptomonedas;estudiantes;universidad;donacion', 'gxchain-blockchain-universidad-stony-brook', 'publicado', null, curtime(), curtime(), curtime());
INSERT INTO `articles` VALUES(NULL, 1, NULL, 3, 'JPMorgan Chase acusado de manipular el oro y la plata como vulgar "crimen organizado"', 'El Departamento de Justicia tardó un siglo para exponer las legendarias bribonerías inimputables de su hoy primer banco de inversiones JPMorgan Chase', 'economia-02.jpg', 'El Departamento de Justicia tardó un siglo para exponer las legendarias bribonerías inimputables de su hoy primer banco de inversiones JPMorgan Chase, supremo especulador de los derivados financieros (''hedge funds''), ahora atrapado en su obscena manipulación de los precios del oro y la plata. ¿Viene una revolución del orden financiero global?. JPMorgan Chase es considerado como el supremo megabanco que maneja hedge funds en el mundo basados en pura especulación financierista que forman parte de la panoplia de los ominosos derivados que han alcanzado la escalofriante cifra de 544 millones de millones de dólares: casi tres veces del valor de las bolsas de valores en todo el mundo y que equivale a más de seis veces el PIB (Producto Interno Bruto) Global de 87,27 millones de millones de dólares. Quizá esté por fenecer una de las trasnacionales financieras mas añejas del planeta con sede en Nueva York que hoy controlan grandes gigabancos como BlackRock, Vanguard Group y StateStreet. JPMorgan Chase constituye el primer banco de EEUU y el sexto en el mundo de acuerdo al ranking de sus activos que ascienden a 2,73 millones de millones de dólares. Según Tyler Durden, de Zero Hedge, el Departamento de Justicia de EEUU acusó a la mesa de tratativas de metales preciosos (oro y plata) de ser una "empresa criminal", como un vulgar "equivalente funcional de las mafias". Zero Hedge se mofa de lo que antes, cuando era expuesto, era señalado como ''teoría de la conspiración''. Los fiscales exhibieron "el masivo esquema de varios años para manipular el mercado de los contratos futuros de los metales preciosos y la defraudación de los participantes en el mercado".

El Departamento de Justicia acusó formalmente a tres mercaderes del megabanco: Michael Nowak (anterior mandamás de su mesa comercial de metales preciosos), Christopher Jordan (quien se trasladó luego a Crédit Suisse y a First New York), y a Gregg Smith. El más mafioso de todos, Blythe Masters, ha sido omitido por el momento.

Brian Benczkowski, asistente del procurador general, comentó a la prensa que "basado en el hecho de que se trató de una conducta que fue extensa en la mesa, que se comprometió en miles de episodios en un periodo de ocho años —que es precisamente el genero de conducta que el estatuto RICO es dado a castigar—". El acrónimo RICO (Racketeer Influenced and Corrupt Organizations: Organizaciones Corruptas e Influenciadas por los Delincuentes) hace temblar al mas pintado mafioso en EEUU.

El portal Bloomberg explaya la enmienda RICO: "una ley que permite a los fiscales capturar las ''empresas criminales'', como la de las mafias, al incriminar a todos [sic] los miembros de la organización por cualquier crimen cometido por un individuo en nombre de la organización". ¿Jaque previo al mate? ¿Irán tan lejos como embargar y/o expropiar los activos de 2,73 millones de millones de dólares y, de paso, fastidiar a sus verdaderos propietarios: los gigabancos BlackRock/Vanguard/State Street?

El lenguaje usado de los fiscales es exageradamente feroz —por tratarse de las joyas bancarias estratégicas que gozaron de la permisividad de los Clinton y Obama—, quienes acusaron a los mercaderes del oro y la plata del banco de operar "una conspiración [sic] en la conducta de los asuntos de una empresa implicada en el comercio interestatal o foráneo mediante un patrón de actividad del crimen organizado", lo cual apunta, según Zero Hedge a una "más profunda acusación del banco" cuando hasta ahora 12 mercaderes "han sido acusados de conspiración manipulativa". Benczkowski no se mordió la lengua: "Perseguiremos los hechos a donde conduzcan, sea entre las mesas aquí o en cualquier otro [sic] banco o arriba [sic] en la institución financiera misma". Si realmente el Departamento de Justicia es consecuente con lo que ha manifestado, pues prácticamente estaríamos hablando de un embargo general de toda la banca de EEUU: una verdadera revolución financiera como cuando Roosevelt embargó el oro, pero que ahora Trump lo haría al revés: embargando los activos bancarios de Wall Street. Un golpe de esta magnitud de parte de Trump, en búsqueda de su atribulada reelección, lo haría inmensamente popular y rebasaría a la senadora Elizabeth Warren del Partido Demócrata, quien ha crecido gracias a su postura en contra de los excesos de Wall Street.

¡La dimensión es enorme!: Trump estaría dando un golpe de Estado Financiero en el corazón mismo de Wall Street y quizá esté arriesgando su vida, no se diga la de su familia entera. De ahí quizá se explique la exagerada ferocidad de sus contrincantes, estimulados por los mega y gigabancos puestos en jaque y que dominan el mercado de Wall Street y buscan defenestrarlo con cualquier pretexto banal o real.

Benczkowski remató que "las acusaciones no deben dejar duda de que el Departamento de Justicia está comprometido a perseguir a quienes socavan la confianza del público inversionista en la integridad de nuestros mercados de materias primas [commodities]". William Sweeney, director asistente a cargo de la oficina de campo en Nueva York del FBI, agregó que la manipulación probablemente impactó a "mercados correlacionados [sic] y a los clientes del banco que representaron" mediante un "esquema complejo en el comercio de metales preciosos de manera tal que afectaron negativamente el equilibrio natural de la oferta y la demanda". ¿Jaque también a la banca europea y latinoamericana? Lo mas interesante es el periodo de investigación de ocho años que inició cuando apenas EEUU llevaba tres años de su grave crisis financiera de 2008, producto de la quiebra de Lehman Brothers, y todavía era presidente Obama quien no tuvo el coraje ni la voluntad de poner orden en Wall Street y en los mercados globales.

No falta quienes aduzcan que se trata de una vendetta de Trump contra sus acosadores y acusadores del fallido Russiagate y que ahora han vuelto a la carga con otras trivialidades que buscan su defenestración (impeachment) bajo cualquier excusa.

En forma extraña le han dado mucho juego al fajo de billetes de 20 dólares que tenía Trump en la bolsa trasera de su pantalón. Cabe recordar que en su sonada entrevista a Play Boy de hace 29 años, Trump, cuando era Demócrata antes de convertirse a Republicano, manifestó que el prefería el efectivo (cash), como casinero que fue, y los bienes raíces, como inversionista inmobiliario en la actualidad, a los juegos financieros bursátiles. El Departamento de Justicia de EEUU no está golpeando a cualquier banco, sino que se fue a la yugular del principal banco global del viejo sistema financiero internacional basado en los ''derivados financieros [hedge funds]'', por lo que el haber expuesto la flagrante manipulación del oro y la plata que dañó a millones de inversionistas en EEUU y en el extranjero es probable que signifique el advenimiento de un nuevo orden financiero global apuntalado por el oro y la plata. A mi juicio, en caso de una reelección de Trump, es probable que se esté preparando la ambientación idónea para impulsar al oro y la plata —en EEUU ya existió incluso un Partido de la Plata en el Siglo XIX —como baluartes del nuevo sistema financiero internacional, al unísono de Rusia/China/India, y que curiosamente formó parte de la plataforma electoral del Partido Republicano en la elección presidencial pasada y que sabe mejor que nadie la grave crisis que padece el dólar.', 'investigacion;fraude;bancos;oro', 'gp-morgan-acusado-manipulacion-oro-plata', 'publicado', null, curtime(), curtime(), curtime());
INSERT INTO `articles` VALUES(NULL, 1, NULL, 3, 'La guerra por el dólar que EEUU perdió: ¿surge una nueva fiebre del oro?”', '"El dólar es nuestra moneda y vuestro problema", dijo una vez en broma el secretario del Tesoro de Nixon, John Connally', 'economia-03.jpg', 'Los bancos centrales europeos ponen fin a su acuerdo sobre el oro que concluyeron en 1999 en Washington y que tenía como objetivo coordinar las ventas del oro. La tendencia de las últimas décadas, cuando los países europeos, con EEUU en la vanguardia, activamente se desprendían de este metal precioso en el altar del dólar, ha cambiado en dirección opuesta.

A finales del primer semestre, todos los bancos centrales del mundo compraron 374 toneladas de oro, marcando un verdadero hito. Los mayores compradores del metal precioso fueron los bancos centrales de Polonia, Rusia, China y Turquía.  De esta manera, protegen sus reservas de oro y divisas de los riesgos asociados con las acciones de los reguladores financieros de EEUU y la Unión Europea, así como de la incertidumbre geopolítica. Los expertos están seguros que el oro se convierte en "una garantía absoluta contra los riesgos legales y políticos".
¿Pero cuando los países se desprendieron del oro y cuáles fueron las razones? "Dólar: nuestra moneda – vuestro problema"

El abandono del patrón oro comenzó en 1944. Hace 75 años, en la ciudad de Bretton Woods, en el estado norteamericano de New Hampshire, delegados de 44 países acordaron crear un sistema monetario mundial: el dólar estadounidense se convirtió en la principal moneda internacional. Su tasa fue fijada con las reservas de oro de Estados Unidos, que en ese momento eran casi el 70% de todas las reservas del mundo. El precio del metal "amarillo" se fijó en 35 dólares por onza troy. Los países miembros mantenían sus reservas principalmente en forma de oro o en dólares, y tenían el derecho de vender sus dólares a la Reserva Federal de Estados Unidos a cambio de oro al precio oficial. Pero con el tiempo resultó claro: en el contexto de la creciente inflación y el déficit del comercio exterior, EEUU no fue capaz de mantener la paridad del oro en el nivel establecido durante mucho tiempo. La situación fue agravada por los gastos de EEUU en la guerra de Vietnam. La caída del sistema Bretton Woods fue inminente: generó problemas como el dilema de Triffin, el creciente déficit comercial de EEUU, que puso en tela de juicio el uso del dólar como moneda de reserva en el sistema financiero internacional. El entonces ministro de Economía y Finanzas de Francia, Valéry Giscard d''Estaing, abiertamente llamaba el sistema de Bretton Woods "un privilegio exorbitante" para los estadounidenses. Los países europeos no estaban dispuestos a continuar pagando las emisiones incontroladas de EEUU. Durante su famoso discurso el 4 de febrero de 1965, el entonces presidente francés Charles de Gaulle dijo:

 "Por qué habría de permitírsele a los países más ricos del mundo monopolizar los beneficios de la creación de reservas internacionales para la financiación de sus propios déficits? ¿Por qué habría que participar el Banco de Francia en la financiación de las políticas de los EEUU, políticas en las que Francia no tenía voz y con los cuales podía estar en completo desacuerdo?". "El hecho de que muchos países, acepten como principio que los dólares son tan buenos como el oro, conduce a los estadounidenses a endeudarse de forma gratuita a expensas de otros países. Porque lo que EEUU debe, lo paga, al menos en parte, con un dinero que solo ellos pueden emitir. Ante las graves consecuencias que se podrían desencadenar en caso de una crisis, creemos que se deben tomar medidas a tiempo para evitarla. Consideramos necesario que el comercio internacional se establezca sobre un patrón monetario indiscutible, y que no lleve la marca de un país en particular. ¿Qué patrón? La verdad es que no se puede imaginar otro patrón que no sea el oro!". La imposibilidad de EEUU de hacer frente a sus compromisos de convertibilidad monetaria, desató en 1968 una verdadera fiebre del oro. Y la empezó de Gaulle quien decidió exigir a EEUU cambiar el oro por los dólares acumuladas en el Banco de Francia, algo que garantizaba el acuerdo de Bretton Woods pese a sus desventajas. Fue inminente que otros bancos centrales del mundo empezaron a exigir lo mismo: devolver dólares a EEUU a cambio de oro. Pero EEUU no planeaba resistir. "El dólar es nuestra moneda y vuestro problema", dijo una vez en broma el secretario del Tesoro de Nixon, John Connally. Pero parece que no era ninguna broma. A finales de julio de 1971, las reservas de oro de Estados Unidos habían caído a un nivel muy bajo. Como respuesta, en 1971 Richard Nixon instauró el famoso "Shock económico",  cancelando unilateralmente los acuerdos de Bretton Woods y suspendiendo la convertibilidad directa del dólar estadounidense con respecto al oro. Asimismo, Nixon impuso un arancel temporal de 10 %, forzando al resto de los países a revalorizar su moneda. Cinco años más tarde, en la conferencia de Jamaica de 1976, el nuevo sistema financiero fue establecido oficialmente. Política deliberada de contención del oro

Expulsar el oro del mercado financiero y frenar la subida de los precios del oro con el tiempo se convertiría en el objetivo principal de EEUU. Lo comprueban las estenografías de la reunión entre el entonces Secretario de Estado de EEUU Henry Kissinger y sus asistentes, publicadas en el sitio web del Departamento de Estado de EEUU: "Mr. Enders: Sr. Secretario, es una oportunidad, debemos tratar de negociar y avanzar hacia una desmonetización del oro, para comenzar a sacar el oro del sistema. Va en contra de nuestro interés tener oro en el sistema... Aunque todavía tenemos reservas sustanciales de oro —alrededor de 11 mil millones—, una gran parte del oro oficial del mundo se concentra en Europa Occidental. Esto les da la posición dominante en las reservas mundiales y los medios dominantes para crear reservas.
Secretario Kissinger: ¿Pero cómo planean hacerlo? Mr. Enders: Hay otra propuesta, que el FMI comience a vender su oro al mercado mundial, y deberíamos tratar de negociar eso. Eso comenzaría la desmonetización del oro. [...] También podríamos hacerlo menos interesante para ellos si empezáramos a vender nuestro propio oro en el mercado, y esto les pondría presión".

Así EEUU empezó a desprenderse del metal precioso activamente, para que los socios europeos hicieran lo mismo. Se vendieron varios cientos de toneladas de las reservas de oro del Tesoro de EEUU. Después siguieron el FMI y los bancos centrales europeos. En cinco años en total los bancos vendieron 1,23 mil toneladas de metal. En los años 80, las ventas se detuvieron y se reanudaron sólo en los años 90. Así ya en diciembre del 2000, el precio de oro cayó a un mínimo histórico de 271 dólares. Al mismo tiempo, la posición del dólar estadounidense en el mundo alcanzó su nivel máximo. El Fénix dorado

La situación cambió drásticamente después de la crisis del 2008, que fue acompañada no sólo de una recesión económica mundial, sino también por la quiebra de las instituciones financieras, que hasta hace poco parecían indestructibles. En particular, en febrero de 2008, en el Reino Unido fue nacionalizado el banco Northern Rock, un mes más tarde el banco estadounidense Bear Stearns fue comprado por JP Morgan Chase por sólo 240 millones de dólares, aunque un año antes su valor se estimaba en más de 30.000 millones de dólares, y en el verano del mismo año, la Reserva Federal de los EE.UU. se vio obligada a salvar a las compañías hipotecarias Fannie Mae y Freddie Mac. La crisis culminó con la quiebra de Lehman Brothers, uno de los principales conglomerados financieros del mundo.
En esas circunstancias, los bancos centrales tuvieron que pensar de nuevo sobre la diversificación de sus reservas y los activos seguros. Según la opinión de algunos expertos, el aumento de la inversión en metales preciosos es una forma de diversificar la estructura de las reservas ante una creciente incertidumbre del comercio mundial y los mercados financieros. Hay algunos que consideran este enfoque como anacrónico. Sin embargo, es imposible no reconocer que en los últimos años, los bancos centrales aumentaron considerablemente sus inversiones en oro. Aparte de la incertidumbre económica y política, las sanciones de EEUU contra países como Turquía, cuando la lira turca cayó en un 20%, o contra China, que se enfrentó con las restricciones y aranceles sobre sus productos, hizo apostar no al dólar sino a otros activos más estables. Los analistas dicen que el oro puede ser considerado como un verdadero "activo antidólar".

"El oro no cambia su naturaleza: puede estar en lingotes, monedas; no tiene nacionalidad, existe desde hace mucho tiempo, y está aceptado por todo el mundo entero por su valor estable. Sin duda el valor de cualquier moneda se determina por conexiones directas o indirectas, reales o supuestas, con el oro", dijo De Gaulle. Y parece que tenía razón. ', 'oro;valor;refugio;EEUU', 'dolar-vs-oro', 'publicado', null, curtime(), curtime(), curtime());

--
-- insert into 'deleted_articles'
--

INSERT INTO `deleted_articles` VALUES(NULL, 1, 2, 1, 'Final de la copa del rey', 'sub título del artículo', 'copadelrey.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pretium sapien id sem scelerisque, in fermentum nibh tempor. In auctor ligula in nunc malesuada convallis. Nulla venenatis iaculis elit et venenatis. Nulla ac velit egestas, sagittis sem vestibulum, auctor justo. Suspendisse sit amet posuere felis. In tempus odio ut quam vehicula, non dictum sem hendrerit. Cras non vulputate magna, vitae facilisis nibh. Etiam aliquet, turpis at porta mattis, nisl leo pellentesque libero, nec convallis purus felis in eros. Maecenas vel nisi ipsum. Sed porttitor est sit amet placerat congue. ', 'kw1;kw2;kw3', 'final-de-la-copa-del-rey', 'publicado', curtime(), curtime());

--
-- insert into 'in_review_published'
--

INSERT INTO `in_review_published` VALUES(NULL, 1, 2, 4, 'Final de la copa del rey publicado y editado', 'sub título del artículo', 'copadelrey.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pretium sapien id sem scelerisque, in fermentum nibh tempor. In auctor ligula in nunc malesuada convallis. Nulla venenatis iaculis elit et venenatis. Nulla ac velit egestas, sagittis sem vestibulum, auctor justo. Suspendisse sit amet posuere felis. In tempus odio ut quam vehicula, non dictum sem hendrerit. Cras non vulputate magna, vitae facilisis nibh. Etiam aliquet, turpis at porta mattis, nisl leo pellentesque libero, nec convallis purus felis in eros. Maecenas vel nisi ipsum. Sed porttitor est sit amet placerat congue. ', 'kw1;kw2;kw3', 'final-de-la-copa-del-rey', 'publicado', curtime(), curtime());




